- name: verify and create user if not already exists
  hosts: web
  become: yes
  tasks:
  - name: expense user exist or not
    ansible.builtin.command: id expense
    register: USER # USER is a variable that gets input from above command
  - name: copy user information
    ansible.buildin.debug:
      msg: "user info {{USER}}"
