- name: install multiple packages
  hosts: local
  connection: local
  tasks: 
    - name: install packages which are in loop
      ansible.builtin.package:
        name: {{ item }}
        state: present
      loop:
      - mysql
      - git
      - ansible
