- name: loos for installing apps
  hosts: local
  connection: local
  tasks:
    - name: install if not and do not install if already exists
      ansible.builtin.package:
        name: "{{ item.name }}"
        state: "{{ item.present }}"
      loop:
      - { name: httpd, state: present }
      - { name: mysql, state: absent }
      - { name: java, state: present}